### ISSUE TITLE
Ucapan Terima Kasih dan Sedikit Saran

### ISSUE THREAD

**Issue by jefrydco** [PhilipPurwoko/CodeHighlighter#3]
Hi, terima kasih telah mengirim submisi challenge Vue.js Intermediate. Saya sangat mengapresiasi kerja keras Mas Philip. Mas juga sudah menambahkan beberapa gaya sendiri. Yang paling suka ada semacam _easter eggs_ berupa _tooltip_ kalau kita _hover_ tulisan Code Highlighternya. Luar biasa Mas!

Mungkin dari saya ada sedikit saran terkait proyek yang Mas kirimkan, yakni di bagian berikut

https://github.com/PhilipPurwoko/CodeHighlighter/blob/fd7a4954ea6607897ddd5fd011ec49788db3b90f/src/components/CodeBlock.vue#L43-L45

Kalau boleh tahu kenapa kah Mas menggunakan `forEach` untuk mengatur nilai dari `languages` yang ada di data? Menurut saya akan lebih baik jika Mas langsung mengatur nilainya secara langsung.

```javascript
this.languages = res.data.data.languages
```

Semangat selalu ya! :muscle:

**Comment by PhilipPurwoko** [comment]
Halo Mas Jefry. Terima kasih atas penilaian dan saran yang diberikan.

https://github.com/PhilipPurwoko/CodeHighlighter/blob/fd7a4954ea6607897ddd5fd011ec49788db3b90f/src/components/CodeBlock.vue#L43-L45

Terima kasih Mas Jefry atas koreksi code nya. Sebetulnya ini adalah project web pertama saya yang menggunakan API. Mungkin, saya kurang jeli saja sehingga menggunakan `forEach` 😆. Yang terpenting saya bisa belajar banyak dari project ini Mas, dan juga bisa menambah portofolio 😄.

**Comment by jefrydco** [comment]
Hi Mas Philip, terima kasih kembali Mas. Nanti semua proyek yang dikirimkan juga akan saya masukkan di daftar https://github.com/jefrydco/awesome-highlight-code.

Saya turut senang mengetahuinya, semangat selalu ya Mas! Kalau ada yg bingung jangan segan untuk bertanya. :muscle:

**Comment by PhilipPurwoko** [comment]
Terima kasih 🙇
